dist/tpm2-abrmd.conf
dist/tpm2-abrmd.service.in
src/include/tabrmd.h
src/tabrmd.xml

This also removes an unused xml attribute from the interface definition.
We can add this back if we fiture out what it was for.

dbus: Cleanup dbus naming for interface / connection / object.

---

configure.ac
man/tpm2-abrmd.8.in
src/tabrmd.c

This borrows heavily from the version string mechanism used in the
tpm2.0-tools project.

tabrmd: Add --version option to display version string.

---

src/tabrmd-priv.h

This constant is defined in glib-2.0 versions >= 2.42. Travis CI
packages a super old version of Ubuntu that provides glib-2.0 version
2.40. So we define this ourselves if it's not already defined for us.

tabrmd-priv: Define G_OPTION_FLAG_NONE if not already defined.

---

man/tpm2-abrmd.8.in

The default port number used by the simulator is 2321. This is the
default port used by the tpm2-abrmd. The man page was wrong though.
Fixed! See
https://github.com/flihp/tpm2-abrmd/commit/267ec43bddd59c50af3277ae49b9b601423aa4e9#commitcomment-22170495

tpm2-abrmd.8.in: Fix bad default port number for socket TCTI.

---

src/tcti-socket.c

The code in the tabrmd already sets these values appropriately. Setting
these as the defaults for the GObject properties is just for clarity.

TctiSocket: Set default host name string / IP and port.

---

test/resource-manager_unit.c
test/tpm2-response_unit.c

Failures were caused by minor changes made in the run up to the
1.0.0 release.

test: Fixup unit tests for ResourceManager and Tpm2Response.

---

test/access-broker_unit.c
test/resource-manager_unit.c

Fixes unclaimed thread resources and an out of bounds read caused by a bad tpm command tag. These are just in the unit tests and were uncovered by valgrind.

Unit fixup

---

Makefile.am
test/thread_unit.c

This test instantiates a test GObject that inherits from the abstract
Thread class. We walk this subclass through the thread _start, _cancel
and _join lifecycle. Additional tests to mock the pthread functions here
would be useful.

unit: Add test to exercise the Thread object.

---

.travis.yml
Makefile.am
m4/ax_valgrind_check.m4
test/resource-manager_unit.c
test/response-sink_unit.c

This series enables valgrind so that `make check-valgrind` runs the unit tests under the valgrind memcheck memory profiler. There are two unit tests, both exercising the Thread lifecycle for derived classes, that had to be removed. These tests both cause a 'critical' error to be thrown up by glib 2.40. They weren't good / valid tests anyways and they should be re-written.

Check valgrind

---

src/tcti-options.h

The EchoTcti was some old debugging infrastructure. It was cleaned out
of the daemon a long time back. We still use it in a few test cases so
the code is still around. It's not used in the tpm2-abrmd though.

TctiOptions: Remove final remnants of the EchoTcti.

---

src/tabrmd.c

The TctiOptions object was instantiated as a side effect of the
parse_opts function. It gets used in the main function immediately after
the call to parse_opts (where the TCTI is instantiated).
It's better form to instantiate this object in main. Then it's passed
into the parse_opts function where the TCTI options are parsed. Then we
use it as a factory to pump out a Tcti object based on the parsed
options.

tabrmd: Instantiate the TctiOptions object in main, not parse_opts.

---

src/session-list.c
test/integration/context-util.c

This patchset fixes some minor findings from clang's scan-build.

Fixes from clang static analyzer

---

configure.ac

Querying pkg-config for the default here made sense at the time but it
breaks distcheck. This is because distcheck does a DESTDIR install and
the default ignores this.
After thinking about this a bit I'm realizing that using pkg-config also
causes "non-standard" behavior in that it will ignore the expected
behavior when overriding ${libdir}.
This patch simplifies this abit defaulting to ${libdir}/systemd/system.

configure.ac: Use hard coded systemd unit dir not pkgconfig variable.

---

Makefile.am

The 'dist' and 'distcheck' targets require these files to build release
tarballs. This patch fixes both targets and 'distcheck' can now be
integrated into the CI infrastructure. Will keep me from doing stupid
stuff in the future like breaking VPATH builds or DESTDIR stuff.

Makefile: Add headers to SOURCE vars and use EXTRA_DIST for the rest.

---

src/util.c

This is intended to prevent the caller from causing a large static
allocation for the 'line' buffer. A line longer than 200 characters will
now produce a warning and print nothing.
We also now allocate the line buffer to 0's since the allocation size is
known at compile time.

util: Initialize data, set sane maximum line length in g_debug_buffer.

---

src/resource-manager.c

This is an exceptional condition that shouldn't happen. But if it does
we return NULL (not an RC) and the ResourceManager will carry on
processing the command like any other.

ResourceManager: If command has wrong code return NULL;

---

.travis.yml

We're currently running 'make check-valgrind' which only returns an
error code if memcheck detects errors in the unit test. If the unit test
itself fails however memcheck will not indicate a failure. So we need to
run both 'make check' to detect failures in the unit tests, and then
'make check-valgrind' to get errors detected by memcheck.

travis: Run 'make check' and dump logs.

---

.travis.yml
configure.ac

By running distcheck we get a full test of the VPATH build stuff, all of
the packaging checks and a run of 'make check' for all of our unit
tests. The only thing distcheck won't do for us (or at least I don't
know how to get it to do this) is to run 'check-valgrind'. So we still
have to do a build manually and run 'check-valgrind'.

build: Integrate distcheck into travis, enable unit tests for distcheck.

---

.travis.yml
README.md
src/access-broker.c
src/command-attrs.c

Enable automated static analysis on the 'coverity_scan' branch. This includes a few fixups necessary to keep coverity from having a heart attack. There are still a few items to fix in the test code but everything under `src/` got a clean bill of health.

Coverity scan

---

CHANGELOG.md
Makefile.am
configure.ac
man/tpm2-abrmd.8.in
man/tss2_tcti_tabrmd_init.3.in
src/include/tabrmd.h
src/include/tcti-tabrmd.h
src/tabrmd-priv.h
src/tabrmd.c
src/tcti-tabrmd.c
src/tcti-tabrmd.map
test/integration/context-util.c
test/integration/main.c
test/integration/test-options.c
test/integration/test-options.h

This patch series adds:
* code to allow the daemon to use a configurable (on the command line) name for the dbus connection
* a new initialization function to allow the TCTI to connect to a configurable bus type and name
* plumbing to allow the integration tests to take advantage of this configuration through the environment

Tss2 tcti tabrmd init full

---

coverity/coverity-model.c

All coverity models should go into this new file. All of our Coverity
false positives come from g_error though so this is all that's in here
for now.

coverity: Add model for g_error to deal with false positives.

---

test/integration/hash-sequence.int.c

Use g_error instead of g_warning. On success return 1 not 1 ... like we
should.

test: Fix return conditions from hash-sequence.int.c

---

src/connection-manager.c

According to https://developer.gnome.org/glib/stable/glib-Hash-Tables.html#g-hash-table-contains
g_hash_table_contains() takes a pointer, not a pointer to a pointer.

Fix duplicate connection id detection

---

Makefile.am
test/integration/tcti-connect-multiple.int.c

This test currently fails due to a bug in the tabrmd. It's listed in
XFAIL_TESTS until the related bug is squashed.

test: Add test case for multiple TCTI connections from a single process.

---

src/include/tcti-tabrmd.h
src/tcti-tabrmd.c
test/integration/context-util.c
test/integration/tcti-connect-multiple.int.c
test/integration/test-options.c
test/integration/test-options.h

Using GBusType directly seemed like the easiest thing to do at the time
but it causes a weird side effect for users: including the tcti-tabrmd.h
header requires that glib headers be on the include path. This is a bit
obnoxious.
This patch hides the GBusType by creating our own enum type to represent
the bus type.
This resolves #93.

tcti-tabrmd: Replace use of glib type in _init_full with local enum.

---

src/tcti-tabrmd.c

If creating a D-Bus connection fails, libtcti-tabrmd calls g_error() which
causes an abort() and the process to be terminated. This function should
not be used for expected errors, and failing to create a connection can
happen if for example the tpm2-abrmd.service was not started.
In this case, the program using the library could decide to fallback using
the device TCTI to access the TPM directly or just handle the error better
than being terminated due a SIGABRT signal.

tcti-tabrmd: Gracefully fail if D-Bus connection is not created

---

Makefile.am
man/colophon.in
man/tcti-tabrmd.7.in
man/tpm2-abrmd.8.in
man/tss2_tcti_tabrmd_init.3.in

man: Fixup wording in the colophon & move common text to colophon.in

---

Makefile.am

This causes these files to be included in release tarballs created by
`make dist`.

build: Add documentation and license file to EXTRA_DIST.

---

src/command-source.c

This is redundant since it's the negation of the initial if.
Conditionals like this are also a bad idea since the code is structured
such that the if or the else must be taken.

CommandSource: Remove 'else if' expression from range check.

---

Makefile.am
m4/ax_valgrind_check.m4

This fixes build failures when running the `check-valgrind` target in a parallel test harness w/o first running the `all` target. This is causing build failures currently.

Fix parallel check-valgrind

---

src/resource-manager.c

ResourceManager: Remove unnecessary call to get a command context.

---

configure.ac

The previous implementation used a default if none was provided by the
caller. If this default (or one provided) doesn't exist then a warning
was printed and the integration tests disabled. This silent disabling of
the tests as the result of what may have been a typo isn't the best
approach.
The new approach is to provide no default. If the caller doesn't provde
a path to a simulator then the integration tests are disabled. If they
do provide a path and it doesn't exist then the configuration is halted
with an error.

build: Remove default value for simulator config.

---

src/command-source.c

The logic previously would reject command buffers with size less than or
equal to 10 bytes (the size of a command / response header). It turns
out that there are valid commands with no parameters (just headers) like
TPM2_GetTestResult.

CommandSource: Allow command buffers with no parameters.

---

.ci/ci-tss-install.sh
.travis.yml

The master branch of the TSS is undergoing updates that break backward
compatability with the 1.x releases. Eventually it will become a 2.0
version. Since we're a consumer of the TSS we need a stable API and
that's 1.x till 2.x is released.

build: Clonse 1.x branch of TSS for travis CI.

---

src/tpm2-command.h
src/tpm2-header.c
src/tpm2-response.c
src/tpm2-response.h
src/tss2-tcti-echo.h
src/util.h

When building tabrmd with a custom install location for sapi,
it couldn't find tpm20.h header file, as it was missing the
sapi prefix.
Correct this by adding it.
Example configure:
./configure --prefix=`realpath ~/tmp` PKG_CONFIG_PATH=`realpath ~/tmp/lib/pkgconfig`

fix sapi lib inclusion

---

.travis.yml

This commit was wrongly accused of causing build failures.
This reverts commit 1f3b3c4a21996d6aa8b726f45e2314183cedfeca.

Revert "Revert "build: Fold travis-ci output for tabrmd build / test.""

---

src/access-broker.c

GCC7 complains that the buffer variable may be used uninitialized, which
causes a build error:
src/access-broker.c: In function ‘access_broker_send_command’:
src/access-broker.c:446:13: error: ‘buffer’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
free (buffer);
^~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2143: src/access-broker.lo] Error 1
make[1]: *** Waiting for unfinished jobs....

AccessBroker: fix build warning in access_broker_send_command() function

---

src/command-source.h

The ResponseSink object currently assumes that all write operations are
atomic. Since we use pipes as the underlying mechanism for sending
responses back to clients we can't assume that writes over PIPE_BUF will
be atomic. This commit is a work around that reduces the maximum buffer
size to PIPE_BUF to guarantee that our write operations will be atomic.

CommandSource: Set BUF_MAX to PIPE_BUF.

---

INSTALL.md
Makefile.am
configure.ac

This is intended to make life for distro packagers easier. Just provide
the configure script with --with-udevrulesprefix="XY-" and the installed
udev rules file name will have the string "XY-" prepended to it.

build: Add configure option to prepend string to udev rules file.

---

RELEASE.md
configure.ac

This makes our source releases usable for those who wish to recreate the
configure script. Of course we don't advise that people do this, though
we shouldn't do anything to actively prevent someone from doing so.

build: Replace use of git in configure.ac with static version string.

---

.gitignore
INSTALL.md
Makefile.am
configure.ac
dist/tpm2-abrmd.preset.in

This allows the caller to specify the default install path for the
preset file, as well as the enable / disable state for the service unit.
By default the install path is `${libdir}/systemd/service-preset`. This
can be overriden using the --with-systemdpresetdir=DIR option. By
default the tpm2-abrmd preset will enable the daemon. It may be disabled
by default using the `--with-systemdpresetdisable` option.

build: Add options to the configure script for the systemd preset file.

---

CHANGELOG.md
configure.ac

The upstream TSS master branch now has API / ABI incompatible changes
with the 1.x stable releases. The tabrmd releases are maintaining
compatibility with the 1.x TSS until a 2.x release is made.

build: Check for compatible SAPI version @ configure time.

---

Makefile.am

The use of these variables can be independent of the check for whether
or not the TCTI library is in use. If the configure script doesn't
include the library they'll be empty. This just reduces the amount of
code in the if / else stuff.

build: Simplify TCTI specific build options.

---

Makefile.am

This is a remnant from before we built a utilty library that we could
link against.

build: Remove unnecessary files from tcti-options_unit build.

---

.travis.yml
Makefile.am
configure.ac
src/tpm2-command.c

This was a bit of a slog. The additional libraries from the 2.0.0 TSS combined with the DESTDIR install required we figure out how to handle the discrepancy between the DESTDIR path and the `dependency_libs` entry in the `*.la` files. Additionally this PR removes a test case from the build. This test case causes gcc linking issues while clang has no problem. It's probably best to make the disabling of this test configurable so devs can run it locally since it works fine on my dev system, only travis seems to be effected.

Master tracks master destdir

---

.travis.yml

Travis-ci upduated their images recently and the new version of clang
(updated from 3.8.4 to 3.9.something) complains about some of the cmocka
initialization stuff. This was fixed between 1.0.1 and 1.1.1.

travis-ci: Upgrade from 1.0.1 to 1.1.1.

---

src/command-source.c
src/command-source.h
src/connection.c
src/connection.h
src/response-sink.c
src/tabrmd.c
src/tcti-tabrmd-priv.h
src/tcti-tabrmd.c
test/access-broker_unit.c
test/command-source_unit.c
test/connection-manager_unit.c
test/connection_unit.c
test/message-queue_unit.c
test/resource-manager_unit.c
test/session-entry_unit.c
test/tpm2-command_unit.c
test/tpm2-response_unit.c
test/tss2-tcti-tabrmd_unit.c

The initial implementation of the communication mechanism used to send
command / response buffers between the daemon and the TCTI library was
pipe2(2). This works well but it requires that we manage two fds on both
ends of the communication channel. As we work toward a more generic /
flexible IPC front end getting the implementation down to a single fd
will make things easier to manage.

tcti-tabrmd: Use local sockets instead of pipes.

---

src/util.c

This should handle temporary interrupts that may happen while we're
in the write syscall. Not sure why we were only doing this for the
read call.

util: Use TEMP_RETRY_FAIL when calling 'write'.

---

Makefile.am
bootstrap
configure.ac

This is a good middle ground between doing this in the configure script
and having a static version string. Github source zip files will still
not work, but this is compatible with the tarballs generated by the
'distcheck' target.

build: Generate version number from git data in bootstrap.

---

Makefile.am
src/command-source.c
src/connection-manager.c
src/connection.c
src/connection.h
src/response-sink.c
src/tcti-tabrmd-priv.h
src/tcti-tabrmd.c
src/tpm2-command.c
src/util.c
src/util.h
test/command-source_unit.c
test/connection_unit.c
test/tss2-tcti-tabrmd_unit.c
test/util_unit.c

There's still a bunch of code that relies on the raw FD like the poll stuff and the connection lookup function but this is a start. Next step is to replace the poll loop with some GSource async IO magic and get rid of the FD usage completely.

Use GSocket in Connection instead of raw FD

---

.gitignore

Changes to the bootstrap script in 7f0d83903b842fc806e007d0c31c2f97cb2d7bd7
cause this file to be generated and shipped in release tarballs.

.gitignore: Ignore VERSION file.

---

src/connection.c
src/connection.h
src/tabrmd.c
src/util.c
src/util.h
test/access-broker_unit.c
test/command-source_unit.c
test/connection-manager_unit.c
test/connection_unit.c
test/message-queue_unit.c
test/resource-manager_unit.c
test/session-entry_unit.c
test/tpm2-command_unit.c
test/tpm2-response_unit.c
test/util_unit.c

By creating the socket pair in the _new function we tighly couple the
Connection object to the IPC mechanism. Moving this out to the place
where we have the rest of the DBus code breaks this coupling.
The majority of this commit are fixups in the unit tests.

Connection: Invert dependency in _new function on connection mechanism.

---

Makefile.am
src/command-source.c
src/command-source.h
src/connection-manager.c
src/connection-manager.h
src/connection.c
src/connection.h
src/response-sink.c
src/tabrmd.c
src/tcti-tabrmd-priv.h
src/tcti-tabrmd.c
src/util.c
src/util.h
test/access-broker_unit.c
test/command-source_unit.c
test/connection-manager_unit.c
test/connection_unit.c
test/message-queue_unit.c
test/resource-manager_unit.c
test/session-entry_unit.c
test/tpm2-command_unit.c
test/tpm2-response_unit.c
test/tss2-tcti-tabrmd_unit.c
test/util_unit.c

This change touches a number of other objects. The CommandSource and
ResponseSink objects now use GInputStream and GOutputStreams
respectively. The ConnectionManager object is also updated to allow
lookups from the CommandSource using the GInputStream associated with
the Connection.
The util module is also updated to use GInputStream and GOutputStream
objects in place of the GSockets.
Finally all of the unit tests that handle Connection objects or do I/O
using the util functions had to be updated.

Command: Replace use of GSocket with GIOStream.

---

src/tabrmd.c
src/tabrmd.h

To avoid unwise configurations or configuration errors, refuse to run as
root by default. A new boolean command line switch allows to override
this behaviour by explicitly adding that switch to the command line.

tabrmd: refuse to run as root by default

---

src/ipc-frontend-dbus.c

This keeps the property setter from falling through and causing GLib
to barf up a CRITICAL error executing the second 'case' statement.

IpcFrontendDbus: Add missing 'break' in property setter.

---

src/ipc-frontend-dbus.c
src/ipc-frontend-dbus.h

The event triggered when the name is lost doesn't provide a reason
as to why. As a result the warning displayed when this happened left
a lot of users guessing as to why. According to the GIO docs, if we
try to acquire a name on DBus and get the name lost event without
first getting the name acquired event then the we have a problem with
permissions in the DBus config.
https://developer.gnome.org/gio/stable/gio-Owning-Bus-Names.html#g-bus-own-name

IpcFrontendDbus: Give better warning when name can't be acquired.

---

.gitignore
contrib/tabrmd.fc
contrib/tabrmd.if
contrib/tabrmd.te

This is necessary because the default Fedora policy for the
unconfined_service_t type (the default context for a service w/o a
private type) doesn't allow the system_dbusd_t type to read / write
from it's stream sockets. Pipes were fine, but not stream sockets.
The policy module added here is a work around. The dbus policy module
doesn't have an interface to allow this type of access and so I've
hacked up this module to allow the operation. The form of the module
isn't right though and it's likely that we'll need to add such an
interface to the dbus module. This will require some collaboration /
vetting with the upstream refpolicy maintainers though.
The build system has not been updated to support building the policy
module so those on Fedora will have to build it manually. This isn't …

SELinux: Add policy module for tabrmd.

---

README.md

This adds details about the migration from the user space tabrmd to use
of the in-kernel implementation. This was the subject of the talk we
gave @ LCP this year so we include a link to the slides as well.

README.md: Add info about tabrmd vs in-kernel RM.

---

man/tpm2-abrmd.8.in

The short option for 'fail-on-loaded-trans' -o should have been -i.
The short option for 'prng-seed-file' -p should have been -g.

man: Fix up incorrect short options.

---

man/tpm2-abrmd.8.in
src/access-broker.c
src/access-broker.h
src/tabrmd.c
src/tabrmd.h

This option causes the daemon to flush all transient objects, loaded
and active sessions from the TPM on startup. The purpose of this option
is to put the TPM into as much of a pristine state as we reasonably
can. We only flush tese particular handle type since they're the only
objects managed by the tabrmd.

Add --flush-all command line option.

---

test/integration/password-authorization.int.c

Usually, platform hierarchy is intended to be locked and
controlled by OEM/ODM. In order to make the test usable on
all systems, including a real TPM hardware, use owner hierarchy
instead of platform hierarchy for the test.
Signed-off-by: Jia Zhang <qianyue.zj@alibaba-inc.com>

[1.x] password-authorization.int: don't use platform hierarchy for the test

---

test/integration/password-authorization.int.c

Usually, platform hierarchy is intended to be locked and
controlled by OEM/ODM. In order to make the test usable on
all systems, including a real TPM hardware, use owner hierarchy
instead of platform hierarchy for the test.
Signed-off-by: Jia Zhang <qianyue.zj@alibaba-inc.com>

[master] password-authorization.int: don't use platform hierarchy for the test

---

test/integration/common.c
test/integration/common.h
test/integration/context-util.c
test/integration/context-util.h
test/integration/main.c

It is necessary to clean up the unused contexts after a testcase
complete with a real TPM hardware, because a real TPM hardware always
has the limited resources, especially the RAM, to keep the transient
entries within it.
Note that the cleanup operation has to be executed in a clean sapi and
tcti contexts, because certain testcase may corrupt the state of tcti
context, causing 0xa0007 error code returned.
Signed-off-by: Jia Zhang <qianyue.zj@alibaba-inc.com>

[1.x] test: remove all contexts after each testcase completes

---

test/integration/common.c
test/integration/hash-sequence.int.c
test/integration/password-authorization.int.c

Much of the code in our test cases came from the legacy tpmclient test
application. The structure of this code isn't ideal and some of this poor
structure came over with it. Now that I'm getting a better understanding
of the authorization mechanisms and the associated structures from the
TSS2 headers I'm re-writing the structure initialization code. This patch
replaces the convoluted and sometimes unnecessary initialization code
from the `tpmclient` application with designated initializers for the
C structures.

test: Simplify session authroization structure initialization.

---

test/integration/context-util.c
test/integration/context-util.h
test/integration/main.c

Normally wrapping this functionality in a function would make sense but
doing so here causes an unwanted dependency from the context-util module
to the common module. This function is only called from the integration
test driver so it's easier and more clear when we  just call the ~3
functions from the integration test driver directly.

test: Remove sapi_fini_from_opts function from context-util module.

---

test/integration/common.c

According to the spec, TPM_HT_LOADED_SESSION and TPM_HT_HMAC_SESSION
have the same value, as do TPM_HT_SAVED_SESSION and
TPM_HT_POLICY_SESSION, but they are used in different context. In
the context of TPM2_GetCapability, LOADED_SESSION_FIRST should be
used instead of POLICY_SESSION_FIRST.
In addition, there is no SAVED_SESSION_FIRST in the spec, so use
ACTIVE_SESSION_FIRST for the query instead .
Signed-off-by: Jia Zhang <qianyue.zj@alibaba-inc.com>

test: correct the property name to be queried

---

RELEASE.md

This change specifically requires signatures be ascii-armored, detached,
and named such that `gpg` will be able to find the tarball if it's in
the pwd. We also add instructions for verifying release tarball
signatures.

RELEASE.md: Improve specificity for release tarball signing process.

---

test/access-broker_unit.c
test/command-attrs_unit.c
test/command-source_unit.c
test/random_unit.c
test/resource-manager_unit.c
test/tcti-device_unit.c
test/tcti-socket_unit.c
test/tss2-tcti-tabrmd_unit.c
test/util_unit.c

This is intended to keep older versions of GCC happy.

test: Use built-in mock with cast functions instead of manual cast.

---

Makefile.am
src/resource-manager.c
src/resource-manager.h
src/session-entry-state-enum.c
src/session-entry-state-enum.h
src/session-entry.c
src/session-entry.h
src/session-list.c
src/session-list.h
test/integration/session-load-from-closed-connection.int.c
test/integration/session-load-from-closed-connections-lru.int.c
test/integration/session-load-from-open-connection.int.c

This PR adds support for multi-process access to sessions. Clients will now be able to:
1) load a saved session from a different tabrmd connection
2) load a saved session from a different tabrmd connection that has since been closed
3) limit the number of unowned (saved by a now closed connection, not yet loaded by aother) sessions 
The use-case driving this requirement are collaborating processes / unix shell pipelines.

1.x session load across connection

---

src/access-broker.c

Simulators 974 and 532 handle the startup routine a bit differently.
If tpm2_startup() fails, try to forward progress anyways.
Fixes:
** (tpm2-abrmd:13686): WARNING **: Tss2_Sys_Startup returned unexpected RC: 0x101
** (tpm2-abrmd:13686): ERROR **: access_broker_sent_tpm_startup failed: 0x101

fix abrmd to work with 532

---

README.md

The URL for the TSS TAB and Resource Manager Specification isn't correct,
it's linked to the TSS 2.0 TPM Command Transmission Interface (TCTI) API
Specification instead.

README.md: fix TSS TAB and Resource Manager Specification URL

---

src/command-attrs.c
src/resource-manager.c
src/tpm2-command.c
src/tpm2-response.c
src/util.c
test/command-attrs_unit.c
test/integration/common.c
test/integration/password-authorization.int.c
test/resource-manager_unit.c
test/tpm2-command_unit.c
test/tpm2-response_unit.c

The SAPI library doesn't support anymore to access TPMAs as struct bitfields.
This causes a lot of build errors when building against the latest tpm2-tss.

Fix build error due trying to access TPMAs as struct bitfields

---

.travis.yml

The tpm2-tss project now has support for test coverage using the autoconf
AX_CODE_COVERAGE macro but this macro isn't available in the Ubuntu image
used by Travis CI so tpm2-tss fails to build.
Fix it by downloading autoconf-archive and installing the missing macro.

travis.yml: Install ax_code_coverage macro to fix tpm2-tss build failure

---

test/access-broker_unit.c
test/command-attrs_unit.c
test/integration/common.c
test/integration/hash-sequence.int.c
test/integration/password-authorization.int.c

Update tests to the new TSS2L_SYS_AUTH_COMMAND
and TSS2L_SYS_AUTH_RESPONSE structures.
This is to reflect the change it TSS:
https://github.com/intel/tpm2-tss/pull/634

test: update to the new SYS_AUTH_COMMAND SYS_AUTH_RESPONSE structs

---

Makefile.am
configure.ac

This pull request by inspired by the same change done by @AndreasFuchsSIT in the tpm2-tss project. 
The first commit is just a trivial fix and the second one enables the silent-rules option by default and prefix commands with AM_V_{GEN,at} to reduce the output.

Enable silent-rules configure option by default

---

.travis.yml

The old version shipped on the travis-ci systems is very old. This will
be required for doing stuff with gcov / lcov.

.travis.yml: Build and install latest autoconf-archive from source.

---

.gitignore
Makefile.am
configure.ac

This adds the '--enable-code-coverage' option to the configure script.
If this option is provided then the script will check for dependencies
and enable the 'check-code-coverage' make target. This will produce the
usual gcov & lcov output.

build: Collect test coverage metrics using AX_CODE_COVERAGE.

---

INSTALL.md
Makefile.am
configure.ac
scripts/run-hwtpm-test.sh

Changelog since V3:
- Use session dbus for the communication between src/tpm2-abrmd and testcase.
- Separate the codes about hw tpm test from int-log-compiler.sh.
- Note: --allow-root option is required for the master branch.
- Here is the diff against int-log-compiler.sh for reviewing scripts/run-hwtpm-test.sh.
```
--- scripts/int-log-compiler.sh	2017-12-15 21:17:41.220889983 +0800
+++ scripts/run-hwtpm-test.sh	2017-12-17 13:24:12.786160958 +0800
@@ -38,18 +38,15 @@
{
cat <<END
Usage:
-    int-log-compiler.sh --simulator-bin=FILE --tabrmd-bin=FILE
+    run-hwtpm-test.sh --tabrmd-bin=FILE
TEST-SCRIPT [TEST-SCRIPT-ARGUMENTS]
-The '--simulator-bin' and '--tabrmd-bin' options are mandatory.
+The '--tabrmd-bin' option is mandatory.
END
}
-SIM_BIN=""
TABRMD_BIN=""
while test $# -gt 0; do
case …
```

[V4][1.x] test: support to run the integration tests on a real TPM hardware

---

CHANGELOG.md
man/tpm2-abrmd.8.in
scripts/int-test-funcs.sh
src/tabrmd.c
src/tabrmd.h

This option was intended as a safe guard against starting the daemon
while some other process had state stored in the TPM. It was an
incomplete implementation however since it fails to address other loaded
objects like sessions. If this functionality is truly needed then it
should be implemented to fail for any loaded TPM state.

Remove --fail-on-loaded-trans command line option.

---

src/tcti-device.c
src/tcti-socket.c
test/integration/context-util.c

Both the device and socket TCTI config structure changed upstream.

tcti: Account for removal of log stuff from TCTI config structures.

---

.travis.yml

This is required by the upstream tpm2-tss.

travis: Install liburiparser-dev.

---

test/tss2-tcti-tabrmd_unit.c

The travis-ci build magically started failing for this test. The root
cause is the initialization of the TCTI fails since the travis-ci
environment doesn't have a dbus system bus to connect to. It never has
though so I'm not sure why it started failing now.
This is a work around to use the session bus instead. We know a session
bus is available since we're the ones who set it up in the .travis.yml
file. It's likely better to create a proper mock object for the proxy
object, or maybe just figure out which function makes the connection and
mock that away.

test: Connect tcti-tabrmd unit test to session bus instead of system.

---

Makefile.am
test/integration/session-load-from-closed-connection.int.c

At the 5th connection that saves and restores a session handle, abrmd
starts flushing handles and thus they are not available after a
client disconection.
This can be seen in the tools side as well with this simple
stress test:
- https://github.com/williamcroberts/tpm2.0-tools/blob/session-tools/stress.sh
Changing this test, to try it 5 times causes the same failure, at 4
it works.

tests: stress test session save/load

---

src/tcti-tabrmd.c
src/tcti-tabrmd.map

Add the dynamic tcti interface, and export the
module information and symbols.
Fixes: #277

tcti: add spport for dynamic init interface

---

src/tcti-tabrmd.c

Fixes white space errors. Adds an explicit check for the conf string. Anything but a NULL string will return an error until we have a way to handle the string.

Cleanup tcti init

---

Makefile.am

The tarballs generated by the make dist target don't include the SELinux
policy module, so add it to the EXTRA_DIST variable.

build: Include SELinux policy module in the release tarballs

---

src/tcti-tabrmd.c

The caller of tss2_tcti_tabrmd_init_config() may pass a NULL conf
string, e.g, launching tpm2_clear without any options, causing a
segment fault.
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>

tcti-tabrmd: fix NULL conf string

---

configure.ac

When the description field is omitted some macros like AC_CONFIG_HEADERS
start to complain.

build: Add the description field when using AC_DEFINE.

---

src/tcti-tabrmd.c

The general form in the spec will be Tss2_Tcti_<name>_Init where 'name'
is the name of the TCTI module.

Rename init_config function to align with naming from upstream.

---

selinux/tabrmd.te

Instead of this is useed dbus interface defined in distrubution policy[1] and also upstream reference policy[2]. This allows you to use raw allow rule in policy and there will be no dependency for distribution policy.
[1] https://github.com/fedora-selinux/selinux-policy-contrib/blob/rawhide/dbus.if#L13
[2] https://github.com/TresysTechnology/refpolicy-contrib/blob/master/dbus.if#L13

[SELinux] Remove gen_require part from tpm-abrmd2 policy.

---

src/tcti-tabrmd.c

tctis should be able to handle a NULL config paramter correctly,
which would indicate to use the default settings.
Currently, abrmd tcti returns an error code if the config
string is NULL.
Correct this by skipping the config string parsing on NULL
and use the defaults.

tcti: handle NULL conf properly

---

Makefile.am
src/tcti-device.c
src/tcti-socket.c
test/integration/context-util.c
test/tcti-device_unit.c
test/tcti-socket_unit.c

The old Init*Tcti functions from the upstream TCTIs have been deprecated
and replace with a standard Tss2_Tcti_<name>_Init function.

tcti: Migrate TCTIs to use new init interface.

---

src/tcti-tabrmd.c

size_t divided by size_t equals size_t. Not sure why I picked a long
unsigned int for the format specifier in the first place.

tcti-tabrmd: Fix format specifier in debug statement.

---

README.md

According to https://github.com/lemurheavy/coveralls-public/issues/116
the github web caching is aggressive to the point of causing the badge
URL provided by coveralls to show old cached values for a very long
time. A number of hacks were proposed but the most sane seemed to be to
use the badge provided by shields.io instead as it doesn't suffer from
the same issue as the one from coveralls.

docs: Use coveralls badge from shields.io instead of coveralls.

---

scripts/int-hardware-setup.sh
scripts/int-test-funcs.sh

The commit 1aa9cbd28d8b
("test: Refactor common code from test support scripts into script
library.") dropped the definition of dbus_daemon_start() so
--enable-test-hwtpm doesn't work as expected.
Additionally, simulator and hardware tests distinguishing from each
other use port number to pass different parameters to tabrmd daemon.
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>

[1.x] test: Fix hardware test failure

---

selinux/tabrmd.te

This pull request contains a cherry-pick from master commit b61499e4a290 ("[SELinux] Remove gen_require part from tpm-abrmd2 policy."), that didn't made to the 1.x branch.
@flihp it would be great if you can cut a minor release with this commit, that way distros can update the tpm2-abmrd package with a correct SELinux policy module.

1.x SELinux: Remove gen_require part from tpm-abrmd2 policy.

---

src/access-broker.c

If Tss2_Sys_Initialize() fails then the sapi_context will leak.

AccessBroker: fix memory leak

---

Makefile.am
src/tabrmd.c
src/tabrmd.h
src/tcti-factory.c
src/tcti-factory.h
test/tcti-factory_unit.c

This is a simple rename of the object and re-enabling of the associated unit test. I couldn't find anything in the VCS that shows this unit test being disabled so it could be that I just never remembered to add it to the test harness in the first place.

Rename TctiOptions to TctiFactory

---

Makefile.am
configure.ac
src/tcti-dynamic.c
src/tcti-util.c
src/tcti-util.h
test/integration/context-util.c
test/integration/main.c
test/integration/session-load-from-closed-connection.int.c
test/integration/session-load-from-closed-connections-lru.int.c
test/integration/session-load-from-open-connection.int.c
test/integration/tcti-connect-multiple.int.c
test/integration/test-options.c
test/integration/test-options.h

I've only ever had a reason to run the integration tests through a TCTI other than `tcti-tabrmd` a few times but it's useful functionality. This RP cleans out the remaining components that linked directly to `tcti-device` and `tcti-socket`. After all of this the integration tests should only link against `tcti-tabrmd` which is the default TCTI. Any other TCTI supporting dynamic loading (like the two we used to link against) can be used by way of the dynamic TCTI loading functions implemented in our local `libtcti-util.a`.
This PR also includes a few cleanup patches that had to go in before the dynamic TCTI stuff.

integration test dynamic TCTI

---

Makefile.am
src/tcti-dynamic.c
src/tcti-dynamic.h
src/tcti-util.c
src/tcti-util.h
test/integration/context-util.c
test/tcti-dynamic_unit.c
test/tcti-util_unit.c

This resolves a bug in the current implementation. Previously we were
dlclosing the TCTI library after tcti context intitialization. This
caused a segfault on subsquent use of the TCTI context since the library
had been dlclosed / unloaded.
This patch ties the lifetime of the library handle (handle returned by
dlopen) to the lifetime of the TctiDynamic object.

tcti-dynamic: dlclose tcti libraries when the TCTI is no longer in use.

---

src/tcti-dynamic.h

This bug causes the daemon, when started without a `--tcti` option, to
fail to initialize a TCTI and thus fail to start.

TctiDynamic: Fix bad default TCTI library string.

---

.travis.yml

This is a new dependency for the ESAPI library that's now in the
tpm2-tss repo.

ci: Install libgcrypt development package.

---

Makefile.am
dist/com.intel.tss2.Tabrmd.service

Maybe you'd like to add these bits. A D-Bus service file allows to start the daemon on demand without having to explicitly enable the system unit.

D-Bus: install a service file to allow on-demand systemd unit activation

---

src/resource-manager.c
test/integration/get-capability-handles-transient.int.c
test/integration/start-auth-session.int.c

tpm2-tss removed YES/NO macros.
Use a gboolean type and TRUE/FALSE to repleace them within the RM.
Update YES/NO to 1/0 in test cases that use that type directly
in SAPI calls.

update YES/NO references

---

.travis.yml

sourceforge has been down on and off for a week. Cmocka.org had some
troubles last week too. Switching to a mirror to try to keep from having
any more down time in the future.

ci: Use mirrored cmocka and simulator tarballs.

---

Makefile.am
test/integration/tcti-double-finalize.int.c

We got a patch recently claiming that multiple calls to the TCTI
finalize function caused a crash. This doesn't seem to be the case since
this test passes but it's always best to have a test in place to ensure
this doesn't happen in the future.

test: Ensure multiple calls to TCTI finalize function doesn't crash.

---

Makefile.am

A generated tpm2-abrmd.preset file is included in the distribution tarball, so
there's no way to change the default preset policy by using a configure option.
This commit causes the build to distribute the template file so that
builds from source will generate the final preset file with data from
the configure script. Additionally, the definition of the
systemdpreset_DATA variable is now conditionally defined alongside the
other systemd stuff.

autotools: Include tpm2-abrmd preset template in distribution tarball

---

man/tss2_tcti_tabrmd_init.3.in

Fix spelling errors in man/ts2_tcti_tabrmd_init.3.in
Fixes #369.

tss2_tcti_tabrmd_init.3: fix spelling errors

---

INSTALL.md

Fix misspelled words in INSTALL.md: attepmt and overriden.
Fixes #374.

INSTALL.md: Fix Spelling Errors

---

INSTALL.md

The INSTALL.md document is unclear about what user to run tpm-abrmd, except not to run as root.
Also document how to run tpm-abrmd as root (although not recommended).
Fixes #356.

INSTALL.md: Document Running tpm2-abrmd as User uid or root

---

man/tpm2-abrmd.8.in

Man page tpm2-abrmd(8) should document the common option to connect
to the TPM2 simulator via a socket.
Fixes #364.

man: tpm2-abrmd(8) Should Document Connection to a Simulator

---

INSTALL.md

Add text explaining that the `configure --with-simulatorbin` option,
does not change the tpm2-abrmd hardware TPM default.
Document how to run tpm2-abrmd with the simulator.
Fixes #366.

INSTALL.md: Document Running tpm2-abrmd with the Simulator

---

INSTALL.md

Point to the document for GNU installation directory defaults.
Add example for --with-systempresetdir option.
Document --datarootdir option (used for Tabrmd.service).
Document that the D-Bus 1 library and header files are required.
Fixes #336.

INSTALL.md: Clarify UID Restrictions to Users tss and root

---

INSTALL.md

Update that the supported Microsoft/IBM TPM2 Simulator Version supported
from 532 to 974.
Also document that it is for Linux.

INSTALL.md: Update Microsoft/IBM TPM2 Simulator Version from 532 to 974

---

test/integration/common.c

This macro is now TPMA_OBJECT_SIGN_ENCRYPT as it is in the spec.

test: Account for rename of TPMA_OBJECT_SIGN upstream

---

src/access-broker.c
test/integration/common.c
test/integration/common.h
test/integration/context-util.c

TSS doesn't export the ABI defines in public heades anymore.
This is a follow up for https://github.com/tpm2-software/tpm2-tss/pull/864

AccessBroker: define ABI version locally

---

dist/tpm2-abrmd.service.in

Remove the unused EnvironmentFile option which specifies a file
that is not delivered.
Fixes #381.

tpm2-abrmd.service: Remove Unused EnvironmentFile Option

---

INSTALL.md
man/tpm2-abrmd.8.in

The library to access the Microsoft/IBM TPM2 simulator has changed,
so change the documentation and man page to reflect this change.
Fixes #386.

Update --tcti Option to Use MS/IBM TPM2 Simulator

---

.travis.yml

It looks like the coverity scan service has reset all of our scan tokens
after the outage. This commit also adds some logic to do the build
instrumented with coverity stuff in a vpath to prevent interference with
the other builds done after.

ci: Refresh coverity scan token encrypted variable & do build in VPATH.

---

.travis.yml

This commit simplifies the build logic for the coverity build.
All of the VPATH stuff for the coverity build has been replaced with a
simple `./bootstrap && ./configure && make`. The typical build logic in
the `script` section of .travis.yml is now short-circuited when we're
doing a build for coverity since we don't care about the usual build /
test cycle, just the scan.

ci: Simplify logic / build for coverity.

---

Makefile.am
man/Tss2_Tcti_Tabrmd_Init.3.in
scripts/int-simulator-setup.sh
src/include/tss2-tcti-tabrmd.h
src/tabrmd.h
src/tcti-tabrmd-priv.h
src/tcti-tabrmd.c
src/tcti-tabrmd.map
test/integration/context-util.c
test/integration/tcti-connect-multiple.int.c
test/integration/test-options.c
test/integration/test-options.h
test/tss2-tcti-tabrmd_unit.c

The two patches in this PR remove the two legacy init functions: `tss2_tcti_tabrmd_init` and `tss2_tcti_tabrmd_init_full`. Once these are removed then the only supported initialization mechanism is the "standard" one: `Tss2_Tcti_Tabrmd_Init`.

Tcti init cleanup

---

src/tcti-tabrmd.c

This now returns the persisted reponse code from previous calls instead
of just blindly returning SUCCESS.

tcti: Fix bad return value from init function.

---

src/tcti-tabrmd-priv.h
src/tcti-tabrmd.c
src/util.c
src/util.h
test/tss2-tcti-tabrmd_unit.c

This commit moves the basics of parsing a string of key / value pairs of
the form "key0=value0,key1=value1,..." from the TCTI module to the util
module. This is the part that parses on "=" and ",". To make this
generic we now provide a callback function that the parsing function
will call passing each parsed key / value pair and a reference to some
caller-provided data.

tcti: Generalize the key / value parsing from the conf string.

---

CONTRIBUTING.md

Getting this requirement clearly stated in a single list entry isn't
easy. Thankfully there are some good resources describing the philosophy
behind this requirement as well as the mechanics of the `git` tool that
make it possible.

docs: Clarify requirement that commits *not* contain unrelated changes.

---

scripts/int-test-setup.sh

shuf is a simple way to generate a random range and is
part of coreutils, like the od/awk/random that it
replaces.
awk itself is useally provided by a non-coreutils like
package. On Ubuntu it defaults to mawk.

test: simplify random number generation

---

src/access-broker.c
src/random.c

Fixes unchecked NULL parameters.
Fixes #425.

Fix Bugs Found by Clang Scan-build Static Code Analyzer

---

INSTALL.md
Makefile.am
configure.ac
dist/tpm-udev.rules

This should be done in the tpm2-tss instead, since conceptually the lower
layers of the stack are the ones that access the TPM character devices.
Also, users may want to access the TPM directly without using a resource
manager in user-space.
Fixes: #412

build: don't install a TPM udev rule

---

test/command-attrs_unit.c

The CMUnitTest type only has 4 membbers and the NULL struct here has 5
members. This isn't required anyways so the cleanest thing to do is to
just remove it.

test: Remove bad NULL struct from CMUnitTest array.

---

scripts/int-test-setup.sh

This commit replaces use of the old tcp:// URI in the tcti conf string
with the new string of key / value pairs. Additionally we now omit the
`host` component since the default is `localhost`.

test: Update int-test-setup.sh to use the new mssim TCTI conf string.

---

.travis.yml
INSTALL.md
Makefile.am
configure.ac
scripts/int-test-setup.sh

The --with-simulatorbin option was a bit awkward as it required passing
the absolute path to the simulator executable. Just having the configure
script check the callers PATH to make sure it's there is a lot cleaner.
This implies that if `--enable-integration` is passed to configure the
caller must have the `tpm_server` executable on their PATH.
Additionally the configure script must export the PATH as it was when the
configure script was executed. The Makefile must then propagate the PATH
to the test script as its executed.
The INSTALL.md file is updated to describe all of this as well as to
document the interaction between this new option with the
`--enable-test-hwtpm` option.

build: Replace --with-simulatorbin option with --enable-integration.

---

src/tpm2-command.c
test/integration/password-authorization.int.c

Change // C++ style comments to
/* C comments for consistency. */
Fixes #443.

Change C++ Style Comments to C Comments

---

m4/flags.m4

The command executed by the AX_CHECK_*_FLAG macro will cause clang to
report a warning when a flag isn't supported. But if we pass this flag
to the build the compilation will fail. So we have to force the warning
to be treated as an error when AX_CHECK_*_FLAG is executed by adding
-Werror to CFLAGS for the check.

build: Treat warnings as errors when checking compiler for flag support.

---

.travis.yml

This reverts commit f05f2a850efc88b99e87da31a2316053fe0fe45f. The issue
with this commit is that, while it enables scan-build, it overwrites the
contents of CFLAGS and causes the build to fail (all -I directives to
the compiler have been lost and so it can't find the TSS@ headers). Odly
enough, because scan-build didn't find any errors (the build failed so
no errors to find) it still reports success. This isn't what we want.
The right solution here will preserve CFLAGS. A simple change like this
however causes the build to pass complete, scan-build to run, but it
then finds a pile of issues and so the build fails. For the short-term
we're reverting this commit and will resubmit it once the issues
identified by scan-build are resolved.
Signed-off-by: Philip Tricca …

Revert "Add scan-build Static Code Analysis to Travis"

---

Makefile.am

The upstream TSS2 libraries now all install headers to this location.
This includes the headers for the mssim and device TCTIs. The tabrmd
header should be in the same location.
this resolves #395

build: Install TCTI header to $(includedir)/tss2.

---

.travis.yml

Took some time but finally jumped through the hoops required to get
Intel to mirror these dependencies. Should insulate us from upstream
outtages and make us better OSS citizens.
This resolves #454 

ci: Use 01.org mirror instead of twobit.us.

---

CHANGELOG.md
man/tpm2-abrmd.8.in
src/tabrmd.c
src/tabrmd.h

This gets us a bit more consistency with the other 'max-sessions' and
'max-connections' options. Update the man page and the CHANGELOG.md as
well.
This resolves #457 

tpm2-abrmd: Rename 'max-transient-objects' option to 'max-transients'

---

Makefile.am
test/integration/auth-session-max.int.c

The logic in the daemon works as expected. This test was just poorly
written. The logic in the test has been sorted out. It's also now using
the constants from the daemons header to determine the default upper
bound and testing accordingly.
this resolves #459 

test: Fix test on per-connection limits to session loading.

---

test/integration/get-capability-handles-transient.int.c
test/tss2-tcti-tabrmd_unit.c

Fix compiler warnings about memory leaks and uninitialized variables.
Fixes #465.

Fix Memory Leak and Uninitialized Variable Warnings

---

src/tcti-util.c

This resolves a bug reported on the mailing list:
https://lists.01.org/pipermail/tpm2/2018-May/000700.html

tcti-util: Use proper SONAME for TCTI dlopen.

---

.travis.yml
src/access-broker.c
src/util.h
test/resource-manager_unit.c
test/tss2-tcti-echo_unit.c
test/tss2-tcti-tabrmd_unit.c

Fix compiler warnings about possible NULL pointer dereferences,
memory leaks, and unused variables.
Fixes #448.

Fix Compiler Warnings

---

Makefile.am

I can't explain why yet but when `distcheck` runs on travis-ci it fails
roughly 50% of the time when executing distcheck. This failure is caused
by a 'core' file that is presumably left behind by a test program. Odly
enough this should also cause the test harness to report a failure. But
since I'm unable to reproduce locally debugging is cumbersome.

build: Ignore 'core' files as workaround for weird travis-ci stuff.

---

src/connection-manager.c

musl libc does not contain 'error.h' which results in compile-time errors in Alpine containers. I believe 'error.h' is specific to GNU libc. Removing the include statement does not appear to cause any problems and allows the build to get further in Alpine.

Remove GNU-libc-specific header

---

src/resource-manager.c
src/session-list.c
src/session-list.h

This function looks identical to the _lookup_handle function but it
behaves very differently. This inconsistency is annoying and the
function itself is awkward. The same functionality can be achieved by
using the current foreach iterator. This produces an extra layer of
indirection when processing closed connections but it's a small price to
pay to get rid of a bad function.

SessionList: Remove _lookup_connection function.

---

.travis.yml

This was a bad idea. It doesn't make the travis output any more
manageable. It generally makes things worse really.

ci: Remove travis output folding stuff.

---

INSTALL.md

Document how to use the SELinux module to use the tabrmd on systems with
SELinux in enforcing mode.
Resolves #481

INSTALL: document installation of the SELinux policy module

---

test/resource-manager_unit.c

scan-build doesn't understand the cmocka asserts. Without this patch
it logs a false positive:
test/resource-manager_unit.c:383:17: warning: 1st function call argument is an uninitialized value
entry = handle_map_entry_new (phandles [i], vhandles [i]);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
As a work-around we can use a conditional and a standard 'assert' which
scan-build understands just fine. There's probably a more elegant way
to inform scan-build about the cmocka asserts but I haven't found anything
concrete yet.

test: Work around scan-build false positive with simple assert.

---

.travis.yml

While debugging #490 it became plane that the current CI script needed some cleanup. Part of this was motivated by the need to just getting meaningful output from the test harness logs when a test fails. While doing this I realized that the CI configuration was also ignoring the results from scan-build which was suppressing a finding from the tool (granted it was a false positive). These two patches fix the issue of the logs remaining invisible when a test fails as well as treating findings from scan-build as failures. 
I've also rolled in some efficiency gains by removing unnecessary build steps that we were using as a crutch. Removing these steps reduces our build time (as reported by travis-ci) from ~12 minutes to ~9 which is pretty significant.

Ci cleanup

---

src/tcti-tabrmd.c
src/util.h

TEMP_FAILURE_RETRY is a non-protable extension to GNU libc.
This PR replaces it with implementation similar to TSS2_RETRY_EXP in
tpm2-tss, but consistent with behaviour described in the GNU C library manual:
https://www.gnu.org/software/libc/manual/html_node/Interrupted-Primitives.html
Adressing issue https://github.com/tpm2-software/tpm2-abrmd/issues/475

Remove TEMP_FAILURE_RETRY call for portability

---

CHANGELOG.md
src/session-list.c

When iterating SessionEntry objects to count the number of sessions
belonging to a Connection the callback was taking references to the
Connection object but not releasing them. This commit adds the
missing call to decrement the reference count.

SessionList: Fix Connection object reference leak.

---

.travis.yml

This is to collect code coverage metrics. The distcheck target will
clean up after itself and delete these. We still execute distcheck for
clang builds, now for gcc we build the 'check' target so that the test
coverage metrics can be sent to coveralls and we don't incur the cost
of two builds.

ci: Build 'check' target when CC is gcc.

---

CHANGELOG.md
configure.ac

This fix updates the URLs to our new github organization. We migrated
away from the 01org github org some time back but these were never
update. Github redirects for us so the old URLs will still bring people
to the right place. Fixing these up is just good housekeeping.

build: Fix bad URLs in configure script.

---

src/random.c
src/random.h

srand48_r, lrand48_r, and drand48_data are GNU extensions and are not portable.
This PR replaces references to these functions and data structure with
functionality documented in the drand48 man page. The drand48 functionality
is a part of POSIX.
Addresses issue https://github.com/tpm2-software/tpm2-abrmd/issues/500

Replace references to drand48_r family of functions for portability

---

src/random.c

Fix for type-punned pointer issue reported by newer compilers.
/src/random.c:153:9: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]

Fix for type-punned pointer reported in newer compilers that enforce strict aliasing

---

src/util.c

When building for the s390 architecture the following warning occurs
which leads to a build error:
```
src/util.c: In function 'write_all':
src/util.c:100:9: error: format '%x' expects argument of type 'unsigned int', but argument 5 has type 'long unsigned int' [-Werror=format=]
g_debug ("writing %zu bytes starting at 0x%" PRIxPTR " to socket 0x%"
^
```
size_t is of a different type than uintptr_t on s390. Due do integer
type promotion the type won't match the PRIxPTR specifier any more after
adding to it.
Arithmetic should be done with the pointer, not the uintptr_t. This will
fix will the warning.
Signed-off-by: Matthias Gerstner <matthias.gerstner@suse.de>

util: fix a format warning that can occur on some platforms

---

Makefile.am

This adds the tests in TESTS_INTEGRATION to the TESTS variable only when
'ENABLE_INTEGRATION' is defined. Additionally the integration test
utility library libtest is added to noinst_LTLIBRARIES now in this
conditional as well. This keeps us from wasting cycles building the
library when the integration tests are disabled.

build: Don't run integration tests If --enable-integration is omitted.

---

Makefile.am

The configure script will set ENABLE_INTEGRATION if the integration
tests should be run (--enable-integration). HWTPM is set if the
integration tests are to be run against the hardware TPM instead of the
simulator. These two conditionals are a bit tangled in that we only care
about HWTPM if ENABLE_INTEGRATION has been set as HWTPM will only be set
if ENABLE_INTEGRATION has been set as well.
This patch moves the HWTPM checks so that they are only in the scope of
the ENABLE_INTEGRATION block.
Fixes #518 

build: Cleanup logic enabling test cases based on configuration options.

---

src/util.c

The value being printed is unsigned but the conversion specifier zd is
used. zd is for signed sizes (aka ssize_t).

util: Fix sign of format specifier in debug message.

---

src/tcti-tabrmd.c

This patch sets all fields in the context that aren't explicitly set to
0.
This resolves #514

tcti: Initialize TCTI context to 0 before setting defaults.

---

configure.ac

When trying to compile tpm2-abrmd using a GLib version built using the Meson build system (e.g. the most recent [glib2 2.58.0-1 for Arch Linux](https://www.archlinux.org/packages/core/x86_64/glib2/)), the build fails with the error
checking for /usr/bin/gdbus-codegen... no
configure: error: *** gdbus-codegen is required to build tpm2-abrmd
The reason for this is that the [check in the configure script](https://github.com/tpm2-software/tpm2-abrmd/blob/d0120ace58d97bc9520c0d558657eaca87ae73b1/configure.ac#L42) relies on the `gdbus_codegen` variable from the GLib pkg-config file. For the Meson build, the value of this variable [has been changed](https://gitlab.gnome.org/GNOME/glib/issues/1521) from just the binary name `gdbus-codegen` to a full path, e.g. `/usr/bin/gdbus-codegen`, which does …

Fix gdbus-codegen lookup for recent versions of GLib

---

src/resource-manager.c
src/session-entry.c
src/session-entry.h
src/session-list.c

This is cleanup / refactoring.

SessionEntry: Move all comparison functions to the SessionEntry module.

---

Makefile.am
test/session-list_unit.c

This commit adds a unit test for the SessionList. The tests in this
module are currently limited to basic insert / lookup / remove
operations.

test: Add unit test for SessionList.

---

.travis.yml

Since we're using the '-|' travis.yml thing for our build steps now we
need to manually 'exit 1' when something fails.
this resolves #536 

travis.yml: Cause failed builds to report failure.

---

.travis.yml

scan-build makes this a bit complex but it's not too bad. This fixes a
bug in the logic used previously that fails the build if the test log
file isn't available. This naively assumption doesn't account for the
fact that a successful build will have removed this file by the time we
check. Instead we should fail if the build directory exists. The build
won't remove the build directory if the build fails so we can debug
stuff.
this fixes more stuff related to #536 

travis.yml: Existence of build directory indicates build failure.

---

src/access-broker.c
src/resource-manager.c
src/session-entry.c
src/session-entry.h
src/session-list.c
src/session-list.h
src/tpm2-command.c
src/tpm2-command.h
src/tpm2-header.c
src/tpm2-header.h
src/tpm2-response.c
src/tpm2-response.h
test/session-entry_unit.c

This commit contains structural changes that are required for handling
the context gap response code. The previous approach was as passive as
possible when it came to handling sessions. The ResourceManager passed
all ContextSave and ContextLoad commands through to the TPM and
extracting the data it needed from them as they passed. This data was
sufficient for us to load and save contexts when clients referenced them
in the handle / auth area of a command.
This design works so long as we don't need to load / save a session
context in between a ContextSave & ContextLoad from the Connection that
owns it. We previously worked around this by refusing to do this. This
was fine since the TPM throws errors if it receives a command that
references sessions that aren't loaded and we were just …

Handle ContextSave and ContextLoad operations for sessions.

---

Makefile.am

build: Do not include llvm profiling file in dist target.

---

.travis.yml

Upstream the tpm2-tss is now defaulting to use openssl as its crypto
library. Supporting this will require a few changes to the ci build.
Best short-term fix is to keep using grcypt until ci is update.

travis-ci: Build tpm2-tss using gcrypt.

---

Makefile.am

The automake noinst_LTLIBRARIES variable was being used to include
the utility library for linking with the TCTI library. When the
integration tests are enabled they must be  added to this variable as
well which causes it to be linked into the TCTI library unnecessarily.
This bloats the shared object. This patch removes the problematic use of
noinst_LTLIBRARIES using libutil directly instead.

build: Stop including libtest in LIBADD for tcti lib.

---

Makefile.am
src/resource-manager-session.c
src/resource-manager-session.h
src/resource-manager.c
src/session-list.c
test/integration/common.c
test/integration/common.h
test/integration/session-gap.int.c

This PR contains
- a test case to trigger and test for the proper handling of the context gap response code
- a bit of refactoring to cleanup the session context management functions in the ResourceManager object
- the logic necessary to handle the context gap response code on behalf of clients

handle TPM2_RC_CONTEXT_GAP

---

test/connection-manager_unit.c

The cast in this test got the type wrong and may be causing problems on
big endian architectures. This test is pretty ugly and should be
possible without the cast. A more permanent fix is future work.

test: Fix bad cast in ConnectionManager unit test.

---

src/resource-manager.c

When building with clang (as we do in the tpm2-tools Travis CI) we observe the
following error:
src/resource-manager.c:988:41: error: missing field 'data' initializer [-Werror,-Wmissing-field-initializers]
TPMS_CAPABILITY_DATA cap_data = { 0 };

Fix building with clang after recent commits

---

Makefile.am

Happy new year! :tada: There is an issue when using the ESAPI from tpm2-tss together with tpm2-abrmd (see #545): When using [`Esys_Initialize`](https://github.com/tpm2-software/tpm2-tss/blob/35c121f6814beef3dbc369e60a2ca189eb381911/src/tss2-esys/esys_context.c#L20) with a `NULL` TCTI context in order to let tpm2-tss use its default TCTI,  the `libtss2-tcti-tabrmd.so` dynamic library is loaded with [`dlopen()`](https://github.com/tpm2-software/tpm2-tss/blob/54090544832a00fb78c65a91fc45e67c77fbd936/src/tss2-esys/esys_tcti_default.c#L135). When the ESAPI context is subsequently finalized with [`Esys_Finalize`](https://github.com/tpm2-software/tpm2-tss/blob/35c121f6814beef3dbc369e60a2ca189eb381911/src/tss2-esys/esys_context.c#L104), the dynamic library is then unloaded with …

build: disable unloading of libtss2-tcti-tabrmd.so

---

.gitignore
.travis.yml
Makefile.am
configure.ac

When using this project in combination with the freshly released Autoconf Archive 2019.01.06, the build fails with a "missing separator" error in the makefile. This is because upstream made a [breaking change](http://git.savannah.nongnu.org/cgit/autoconf-archive.git/commit/m4/ax_code_coverage.m4?id=b5a2d69f7a7e0133733673586231b88464a98d58) by removing `@CODE_COVERAGE_RULES@` and replacing it with `include $(top_srcdir)/aminclude_static.am`, see the [documentation](https://www.gnu.org/software/autoconf-archive/ax_code_coverage.html) for reference.

build: update to ax_code_coverage.m4 version 2019.01.06

---

.travis.yml
Makefile.am

Solves:
$ DISPLAY= make check
FAIL: test/tss2-tcti-tabrmd_unit
** (process:17633): CRITICAL **: 23:53:22.403: failed to allocate dbus proxy object:
Error spawning command line ?dbus-launch --autolaunch=4f9189e347d5cdf343
Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>

tests: run without X

---

.travis.yml

Coveralls integration was broken by some changes around
54035b7ea2d58c8dd2337c032b0d7bc5b4ee4a62. This commit restores coveralls
to a functional state. Code coverage is only enabled for builds with
clang. The clang build has also been changed to build the 'check' target
instead of 'distcheck'. This is required because a successful
'distcheck' build will cause the build directory to be deleted before we
can run coveralls (the source of the original issue).

ci: Fix coveralls.

---

src/ipc-frontend-dbus.c

When started via dbus activation, it can happen that a request is
recieved before dbus_daemon_proxy is set by on_get_dbus_daemon_proxy. In
that case, get_pid_from_dbus_invocation has no proxy and fails.
That results in an error on the client side:
```
** (process:521): WARNING **: 00:02:34.701: Failed to create connection
with service: GDBus.Error:com.intel.tss2.Tabrmd.Error.Internal: Failed
to get client PID
ERROR: tcti init allocation routine failed for library: "tabrmd"
options: "(null)"
ERROR: Could not load tcti, got: "tabrmd"
```
Fix this by registering the name only when the proxy is initialized
already.
I've tested this with a loop that starts tpm2-abrmd and uses tpm2_getrandom to start it via bus-activation.

ipc-frontend-dbus: only own bus name after intializing dbus_daemon_proxy

---

test/integration/test-options.c

We don't pull data from 'argv' in this case, we use the environment
instead.

test: Fix misleading / inaccurate comment in test-options.

---

configure.ac

For AC_ARG_ENABLE/AC_ARG_WITH the default ACTION-IF-FOUND is to set $enable_feature to $enableval.  This does not have to be done explicitly.
After applying this change, the differences between the old and new configure look so:
```diff
--- configure.old   2019-03-08 21:07:15.966051490 +0000
+++ configure.new   2019-03-08 21:08:46.493295523 +0000
@@ -12670,7 +12669,7 @@
if test "${enable_unit+set}" = set; then :
-  enableval=$enable_unit; enable_unit=$enableval
+  enableval=$enable_unit;
else
enable_unit=no
fi
@@…
```

configure.ac: remove some implicit defaults in AC_ARG_ENABLE

---

configure.ac

* don’t print after ./configure --help » --enable-X that feature X is disabled by default as this is implicit.
* AC_ARG_ENABLE: handle test-hwtpm the Autoconf way

configure.ac: tweaks

---

src/tabrmd.c
test/tcti-util_unit.c

Found by http://www.catb.org/~esr/deheader/ .

deheader: remove double #include’d headers

---

Makefile.am
src/tcti-factory.c
test/tcti-factory_unit.c

The code checks the return value and assumes that the context has been
set to a non-NULL value if the response code indicates success. Most
static analysis tools don't look down into the 'tcti_util_dynamic_init'
function to see that this is safe however. Adding an explicit check
comes at nearly no cost and makes the code clear. Some cleanup was
required in the unit test that relied on the old behavior as well.

tcti-factory: Add check for null after TCTI initialization.

---

test/integration/password-authorization.int.c

Much easier reading. Rules for implicit initialization cause size fields
to be zero initialized (per c99).

test: Initialize the TPM2B_NV_PUBLIC structure using designators.

---

Makefile.am
configure.ac
dist/tss2-tcti-tabrmd.pc.in

Apply the changes made upstream in https://github.com/tpm2-software/tpm2-tss/pull/1372 and https://github.com/tpm2-software/tpm2-tss/pull/1384 to tpm2-abrmd:
- Use `AC_CONFIG_FILES` instead of `sed` for variable substitutions.
- Define variables for `libdir` and `includedir` in the pkg-config file and use `-I` and `-L`. This is standard practice, see the [example pkg-config file](https://people.freedesktop.org/~dbn/pkg-config-guide.html#using).
- Use `PKG_INSTALLDIR` to determine the pkg-config directory, which allows changing it with `./configure --with-pkgconfigdir`.

Use AC_CONFIG_FILES for variable substitution, improve pkg-config file

---

src/tabrmd-options.c
test/tabrmd-options_unit.c

The comment above this function clearly states the reason for these
return values. This was however missed in this refactoring. This fix
includes a small change to free the GOptionContext as early as possible.
This allows us to eliminate the final conditional returning the status
from the last function call directly.
This allows us to eliminate one of the unit tests without affecting the
coverage metrics.
This resolves #625 

tabrmd-options: Fix bug introduced in c5e66b78de.

---

Makefile.am
configure.ac

Currently the linking of [`libutil`](https://github.com/tpm2-software/tpm2-abrmd/blob/0611ebceac45f113365af37664d45cf0b5780a1b/Makefile.am#L193) relies on the fact that the upstream tpm2-tss pkg-config file explicitly requires tss2-mu. Since this is wrong and will be changed upstream, but we need access to the marshalling functions, explicitly link against tss2-mu. See https://github.com/tpm2-software/tpm2-tss/pull/1417 for a more detailed discussion.

build: link libutil against tss2-mu

---

src/thread.c

`pthread_join` can crash if called with an invalid thread handle, so we test the handle as in `thread_start` and `thread_cancel`. This fixes the test failure reported in #627.

thread: test if thread handle is valid before joining

---

Makefile.am
configure.ac

According to `ldd -u -r` D-Bus is not needed and everything compiles and runs file without it. Additionally remove `TCTI_DEVICE_CFLAGS`/`TCTI_DEVICE_LIBS` and `TCTI_SOCKET_CFLAGS`/`TCTI_SOCKET_LIBS` since they aren't defined anywhere.

build: remove D-Bus dependency

---

dist/tss2-tcti-tabrmd.pc.in

As in https://github.com/tpm2-software/tpm2-tss/pull/1417, move the dependencies from `Requires` to `Requires.private` and add further necessary dependencies according to the Makefile.
Like https://github.com/tpm2-software/tpm2-tss/pull/1417, the first commit breaks the public API. However the impact is much smaller than for tpm2-tss since libtss2-tabrmd-tcti is usually not linked, but loaded with `dlopen()`. I found no projects using the pkg-config file within the tpm2-software organisation, so nothing will break here.
The second commit is completely backwards-compatible since it only adds new necessary dependencies. It is pending #630 to actually remove the uncessary libdbus-1 dependency.

pkg-config: sort out dependencies

---

configure.ac

Hi,
1. Use AC_USE_SYSTEM_EXTENSIONS and let autoconf detect system pre-processor settings instead of hard-coding them
2. Add --disable-defaultflags to allow downstream to control flags, sync with other tpm2 build systems. This requires for downstream maintainers, I am of Gentoo.
Thanks!

Minor build improvements

---

Makefile.am

All of but one of the files listed in the SOURCES variable are already
built as part of libutil. No use in building these again.

build: cleanup response-sink unit build rules

---

.gitignore

build: Ignore m4 file imported by autoconf *_EXTENSIONS

---

Makefile.am
dist/tss2-tcti-tabrmd.pc.in

This isn't explicitly required. We still end up linking against
libpthread on account of GIO_LIBS but the TCTI does not use pthreads
directly.
This is resolves #633

build: Remove unnecessary pthread lib from TCTI dependencies.

---

Makefile.am

This isn't explicitly required. We still end up linking against
libpthread on account of GIO_LIBS but the TCTI does not use pthreads
directly.
This is related to #633

build: Simplify unit test CFLAGS and LIBADDs.

---

INSTALL.md

This clarifies documented dependencies that may have caused confusion resulting in #641 

docs: Update references to required libraries from tpm2-tss.

---

configure.ac

Previously the configure script would indicate that the integration
tests would be executed even when they were disabled. This commit fixes
this such that the output accurately describes the state of both the
--enable-integration and the --enable-test-hwtpm flags.
This resolves #604 

build: fix misleading output when integration tests are disabled

---

src/logging.h
src/util.c

Fix two alerts uncovered by lgtm.com: add a [header guard for `logging.h`](https://lgtm.com/projects/g/tpm2-software/tpm2-abrmd/snapshot/bd4a3d154e6555b86ca83c9b6ea85e256ac0b0cb/files/src/logging.h#x2777fce244dcef2f:1) and fix an [incorrect error check in `util.c`](https://lgtm.com/projects/g/tpm2-software/tpm2-abrmd/snapshot/bd4a3d154e6555b86ca83c9b6ea85e256ac0b0cb/files/src/util.c#x6b4a6191a554e98f:1).

Fix LGTM alerts

---

.travis.yml
configure.ac

To fix FORTIFY_SOURCE requiring optimization errors:
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
|    ^~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:2451: src/tabrmd.o] Error 1
Add -O2 to the flags.
Fixes: #652

configure: add -02 to flags

---

.travis.yml
bootstrap
configure.ac
src/command-source.c

Upstream tpm2-tss has been using these macros for some time. This resolves #640. The only interesting stuff here is that we must now explicitly configure the clang / scan-build build to enable debug per guidance here: https://clang-analyzer.llvm.org/scan-build.html#recommended_debug

Release debug macros

---

CHANGELOG.md

This commit updates the changelog for the impending 2.3.0 release. This is a minor release as we're adding a new dependency on the new-ish `libtss2-tctildr` from the tpm2-tss repo. This commit *MUST* be updated with the release date before the merge.

CHANGELOG.md: Update changelog for up-coming 2.3.0 release.

---

configure.ac
scripts/int-test-setup.sh

Use `ss` instead of the deprecated `netstat` in the integration tests like it is already done for [other tpm2-software projects](https://github.com/tpm2-software/tpm2-tss/pull/1234).

test: replace netstat by ss

---

src/tabrmd-init.c
src/tabrmd-init.h
src/tabrmd.c
test/tabrmd-init_unit.c

When the IPC mechanism fails to connect the tabrmd-init module receives
an event from the IpcFrontend object and then kills off the GMainLoop.
The current implementation provides no way for the main function to know
why the loop was killed off and so the it exits with a status of 0
(EXIT_SUCCESS) which causes systemd to restart the daemon. This causes a
restart loop.
This patch adds a boolean to the gmain_data_t structure that the
callback sets when the IPC disconnects. This allows the main function to
check for the flag when the GMainLoop terminates and return a meaningful
exit code (EX_IOERR). This exit code will prevent systemd from trying to
restart the daemon.
This resolves #670 

tabrmd-init: Exit with EX_IOERR when IPC fails to connect.

---

dist/tpm2-abrmd.service.in

In testing in an unusual boot scenario it was discovered that
tpm2-abrmd.service was starting before udev had changed ownership
of the TPM device from root to TSS.  This patch changes the
Systemd unit file to force a udev settle before starting the
resource manager service.
Signed-off-by: Steven Clark <davolfman@gmail.com>

Hold Resource Manager until tpm is accessible

---

selinux/tabrmd.te

Updated the current SELinux policy with an SELinux boolean
`tpm_abrmd_can_network_connect` which uses the `tcs_port_t` restriction
for external system connectivity.
Fixes #657
Signed-off-by: Trevor Vaughan <tvaughan@onyxpoint.com>

Update SELinux policy for network TCTI connections

---

.lgtm.yml
.travis.yml

Like the ESAPI, the FAPI is currently not used an pulls in additional dependencies (curl and json-c), see https://github.com/tpm2-software/tpm2-tools/pull/1877, so disable it when building tpm2-tss.

ci: disable building the FAPI for tpm2-tss

---

selinux/tabrmd.te

To use the mssim TCTI the daemon must be able to connect to it. The
simulator binds to ports 2321 and 2322 by default. Neither of these are
reserved ports and so they're labeled 'unreserved_port_t' (the default
for ports 1024-32767, and 61001-65535). This commit adds the required
allow rule in a tunable block guarded by a new boolean:
'tabrmd_can_network_connect'. This boolean is disabled by default so use
of mssim TCTI will require enabling it.
Additionally the daemon may need to resolve network names as part of
connecting to the simulator. The available interface from sysnet cannot
be used from within the 'tunable_policy' block (no clue why) and since
this is a largely innocuous thing for a system daemon to do we place it
outside the tunable block.
Signed-off-by: Philip Tricca …

selinux: Allow name resolve and optional unreserved port name_connect.

---

src/access-broker.c

If calling Tss2_Sys_GetCapability() to get the TPM capabilities fail, the
access_broker_get_tpm_properties_fixed() function calls g_error() which
emits a signal that terminates the tpm2-abrmd process.
This leads to a core dump and a crash being reported in the journal. Since
the service is D-Bus activated, the daemon will be started for each D-Bus
message which makes the issue even more annoying for users.
So instead of killing the process, just log a warning and return an error
message to the access_broker_get_tpm_properties_fixed() function callers.

AccessBroker: Gracefully fail if GetCapability doesn't succeed

---

.travis.yml

Upstream tpm2-tss reworked their libgcrypt detection in autoconf adding
the use of the AM_PATH_LIBGCRYPT macro. Previously the dependency on
gcrypt was only apparent if the source tree was configured to use it
(instead of the openssl default). Using this macro however causes the
bootstrap process to be dependent on libgcrypt-dev (where the macro
lives). This requires that we install libgcrypt-dev on CI workers even
though we're not even building libtss2-esys (the library that depends on
the crypto stuff).

ci: install libgcrypt-dev in CI worker

---

.travis.yml

upgrade travis-ci worker to bionic, update TPM simulator to version 1332 due to build failures with newer compilers

Travis bionic

---

.travis.yml

This commit adds new entries in the build matrix for arm64 arch builds
using both clang and gcc. On arm64 we must install the libltdl-dev
package as well to get the LT_LIB_DLLOAD macro.

ci: Add arm64 arch to build matrix.

---

.travis.yml

This commit adds new entries in the build matrix for ppc64le builds
using both clang and gcc.

ci: add ppc64le arch to build matrix

---

selinux/tabrmd.te

In Fedora, we have the following SELinux AVC error:
Mar 07 09:18:35 river audit[1078]: USER_AVC pid=1078 uid=81 auid=4294967295 ses=4294967295 subj=system_u:system_r:system_dbusd_t:s0-s0:c0.c1023 msg='avc:  denied  { send_msg } for msgtype=method_return dest=:1.558 spid=8554 tpid=8550 scontext=system_u:system_r:tabrmd_t:s0 tcontext=system_u:system_r:fwupd_t:s0 tclass=dbus permissive=0 exe="/usr/bin/dbus-daemon" sauid=81 hostname=? addr=? terminal=?'
It is caused by fwupd not being able to send D-Bus messages to tpm2-abrmd,
so allow them to communicate over D-BUS to prevent this SELinux AVC error.

selinux: allow fwupd to communicate with tpm2-abrmd

---

.gitignore

build: Add selinux policy module to .gitignore.

---

.travis.yml

We switched from coveralls to codecov due to auth issues a long time
ago.

build: Remove step installing cpp-coveralls on build workers.

---

Makefile.am
configure.ac
src/tcti.c
src/tpm2.c
src/util.h

The logging in the lower layers that make calls to Tss2_Tcti_* and
Tss2_Sys_* functions was a bit fragmented. This commit adds a common
logging macro that uses libtss2-rc to decode the response codes when
appropriate. Some minor cleanup is included as well.

libtss2-rc: Add macro to log erro RCs from calls to Tss2_* functions

---

src/session-entry.c
src/session-entry.h

These functions were added back in
e37e33ebb32de8811b25bebcc756c7ddc9ed732c but appear to have never been
used.

session-entry: remove unused functions

---

src/util.h

util: include inttypes as required by the RC_WARN macro

---

.cirrus.yml
README.md
configure.ac
scripts/int-test-setup.sh
src/tpm2-header.h
test/command-source_unit.c
test/connection-manager_unit.c
test/connection_unit.c
test/integration/tpm2-command-flush-no-handle.int.c
test/tcti-tabrmd-receive_unit.c
test/util_unit.c

* Add include of system endian header file
* configure.ac: add a socket tool check specific to FreeBSD
* tests: make tests more portable

Enable unit and integration tests on FreeBSD

---

src/resource-manager.c
test/resource-manager_unit.c

- Add transient handle debug info
- Fixes: #719: If a transient vhandle is referenced twice in a command we load it only once and flush that loaded object. Previously, we loaded it twice but leaked one loaded object.
Needs backporting to bugfix branches...

Fix double use of transient handles and debug statements

---

dist/tpm2-abrmd.service.in
src/resource-manager.c

The Standard output type "syslog" is obsolete, causing a warning since systemd
version 246 [1].
Please consider using "journal" or "journal+console".
[1] https://github.com/systemd/systemd/blob/master/NEWS#L101
Signed-off-by: SZ Lin (林上智) <szlin@debian.org>

Remove obsolete setting regarding the Standard Output and Fix typo

---

.lgtm.yml

Since TSS commit:
- https://github.com/tpm2-software/tpm2-tss/commit/56f91c8aad91c7b100c6dd08812d051d738c7a01
--disable-esapi was changed to --disable-esys, update the LGTM script so
ESYS is disabled and thus things like libcrypto won't be required.
Fixes LGTM error:
[2020-12-30 16:46:28] [build-err] ++ ./configure --prefix=/opt/work/lgtm-workspace/installdir/usr --disable-doxygen-doc --disable-esapi --disable-fapi
[2020-12-30 16:46:28] [build-err] configure: WARNING: unrecognized options: --disable-esapi
<snip>
[2020-12-30 16:46:38] [build] checking for LIBCRYPTO... no
[2020-12-30 16:46:38] [build-err] configure: error: Package requirements (libcrypto) were not met:
[2020-12-30 16:46:38] [build-err] Package 'libcrypto', required by 'virtual:world', not found
[2020-12-30 16:46:38] …

LGTM: fix tss configure flag

---

.ci/get_deps.sh
.github/workflows/docker.yml
INSTALL.md
Makefile.am
configure.ac
dist/tpm2-abrmd.service.in
man/tpm2-abrmd.8.in
scripts/int-test-funcs.sh
scripts/int-test-setup.sh

`libtss2-tcti-swtpm` is available in tpm2-tss 3.0.0. Keep support for `libtss2-tcti-mssim` to allow running the integration tests with older tpm2-tss versions as well, but prefer swtpm if it is available.

test: add support for swtpm simulator and switch CI to it

---

src/resource-manager.c

Clean up potential double free found by coverity in
resource_manager_load_session_from_handle. If flush_session has been
called, don't call session_list_remove which is already called in
flush_session.
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>

ResourceManager: Avoid double free in resource-manager.c

---

test/integration/context-util.c

Compilation with GCC 10.2.0 fails with the warning/error:
```
test/integration/context-util.c: In function ‘tcti_free_from_opts’:
test/integration/context-util.c:131:13: error: unused variable ‘rc’ [-Werror=unused-variable]
131 |     TSS2_RC rc;
|             ^~
```
Not sure why this is not caught by CI, I'm guessing it's due to different compiler versions?

test/tcti-connections-max.int: remove unused variable

---

configure.ac
dist/tpm2-abrmd.service.in

1. Require tpm2-tss 2.4.0 for the systemd TAG in the udev rules. This will create a device unit we can tether a dependency to.
2. Rebase PR #683 on current master
3. Drop the ConditionPathExistsGlob, since the device unit should provide us the needed dependency and the glob could be triggered by non /dev/tpm0 device.
Fixes: #704

remove udev settle

---

.ci/coverity.run

1. Use a fixed scan file over wild cards and hardcodes.
2. Fix copy+paste references to pkcs11
3. Update Project as coverity didn't handle 01org-->tpm2-software org
rename.

COV: fix submission script

---

src/tabrmd-options.c

when starting tpm2-abrmd, one will see the following warnings:
** (process:1417080): WARNING **: 11:00:56.205: tcti_conf before: "(null)"
** (tpm2-abrmd:1417080): WARNING **: 11:00:56.205: tcti_conf after: "mssim"
These aren't really warnings, but debug output, so change the log level
to debug.
Fixes: #762

tcti: drop superfluous warning messages

---

.cirrus.yml

There are some weird CI problems:
https://cirrus-ci.com/task/6694657062076416?command=main#L514
Update image version to stable FreeBSD12.2 version to fix them.

cirrus: update image version

---

src/ipc-frontend-dbus.c
src/tabrmd.xml
src/tcti-tabrmd.c
test/tss2-tcti-tabrmd_unit.c

The CreateConnection call takes two out params - fds, which is an array
of file descriptors, and id - connection id of type uint64.
Additionally the client file descriptor, created in the daemon process,
is returned to the client by the virtue of using
g_dbus_method_invocation_return_value_with_unix_fd_list() on one side
and g_dbus_proxy_call_with_unix_fd_list_sync() on the other, which also
takes and returns file descriptors array.
This makes the fds dbus call param redundant so let's remove it.

tcti: remove extra out param from CreateConnection dbus call

---

src/session-entry-state-enum.c

According to the [GLib documentation for `g_once_init_enter()`](https://developer.gnome.org/glib/unstable/glib-Threads.html#g-once-init-enter):
> While `location` has a `volatile` qualifier, this is a historical artifact and the pointer passed to it should not be `volatile`.
With GCC 11, making the variable volatile produces a compiler warning/error:
```
src/session-entry-state-enum.c: In function ‘session_entry_state_enum_get_type’:
/usr/include/glib-2.0/glib/gatomic.h:117:5: error: argument 2 of ‘__atomic_load’ discards ‘volatile’ qualifier [-Werror=incompatible-pointer-types]
117 |     __atomic_load (gapg_temp_atomic, &gapg_temp_newval, __ATOMIC_SEQ_CST); \
|     ^~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gthread.h:260:7: note: in expansion of macro ‘g_atomic_pointer_get’
260 | …
```

session-entry-state-enum.c: make g_once_init_enter arg non-volatile

---

.lgtm.yml

The version information needs a full clone of the git repo
as it uses git describe in configure.ac

lgtm: use git clone over tarball

---

src/tcti-tabrmd.c

When an error happens in `tcti_tabrmd_read`, Glib reports:
(process:905338): GLib-WARNING **: 06:59:08.971: GError set over the
top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is
NULL before it's set.
The overwriting error message was: Error receiving data: Connection
reset by peer
This warning was reported on https://github.com/tpm2-software/tpm2-pkcs11/issues/705
Fix the warning by initializing `error` correctly.

tcti: initialize GError to NULL

---

test/thread_unit.c

This fixes the following compiler warning/error:
```
test/thread_unit.c: In function ‘test_thread_run’:
test/thread_unit.c:72:1: error: no return statement in function returning non-void [-Werror=return-type]
72 | }
| ^
```

test/thread_unit.c: add missing return value for test_thread_run()

---

CHANGELOG.md
configure.ac

This is a redundant check. AC_CHECK_PROG already finds the program on
path and ensures that it is executable.

build: Remove use of 'which' to check for existence of gdbus-codegen.

---

selinux/tabrmd.if

Policy need rules to communicate with keylime.
AVC:
allow keylime_agent_t tabrmd_t:dbus send_msg;
allow keylime_agent_t tabrmd_t:unix_stream_socket { getattr getopt read write };
Create new interfaces to allow keylime
communicate with keylime.
[keylime-selinux](https://github.com/Koncpa/keylime-selinux)

SELinux: Add new interfaces for communication with keylime

---

selinux/tabrmd.if

In name of interface in SELinux policy is
typo issue.
Signed-off-by: Patrik Koncity <pkoncity@redhat.com>

Fix in SELinux interface file a typo

---

RELEASE.md

update mailing list

---

selinux/tabrmd.te

allows for systemd hardenings to be applied to the daemon

selinux: call init_nnp_daemon_domain for domain 
