src/message-queue.c
src/message-queue.h
src/resource-manager.c
src/response-sink.c
test/message-queue_unit.c

Cleaning up the MessageQueue object a bit.

Message queue cleanup

---

src/message-queue.h
test/message-queue_unit.c

A bit of cleanup and a new unit test to exercise enqueue / dequeue between two threads.

Message queue thread

---

INSTALL.md

INSTALL.md: Add information about enabling the unit / integration tests.

---

Makefile.am
test/integration/manage-transient-keys.int.c

test: Port manage-transient-keys test to use integration test harness.

---

.travis.yml
Makefile.am
scripts/int-log-compiler.sh

this resolves #85. Ran into the issue while working on a test case for #83

Retval propagate xfail tests

---

CHANGELOG.md
Makefile.am
man/tpm2-abrmd.8.in
src/connection-manager.c
src/connection-manager.h
src/connection.c
src/connection.h
src/random.c
src/random.h
src/tabrmd.c
src/tabrmd.h
src/tabrmd.xml
src/tcti-tabrmd-priv.h
src/tcti-tabrmd.c
test/command-source_unit.c
test/connection-manager_unit.c
test/connection_unit.c
test/resource-manager_unit.c
test/session-entry_unit.c
test/tss2-tcti-tabrmd_unit.c

revert commits that broke client multi-connection & add cmd line seed file option

---

src/tabrmd.c

Calling g_main_loop_is_running() from an asynchronous signal handler
results in undefined behaviour. See documentation of
g_unix_signal_source_new():
https://developer.gnome.org/glib/stable/glib-UNIX-specific-utilities-and-integration.html#g-unix-signal-source-new
This commit switches over to glib based signal handling. This also
eliminates the need for the global variable holding the pointer to the
main loop data structure.

switched signal handling from sigaction() to g_unix_signal_add()

---

INSTALL.md

The dependency list was missing a reference to the TSS. This has been
added and the dependencies for the test harness have been broken out
into their own list since they're not strictly required to build the
daemon.
Documentation for the creation of the tss user / account has been moved
to the front of the instructions.
Documentation for the configuration options have been integrated into
the section describing the configuration process. Previosly these were
left till the end of the document and this was causing some confusion.
They've also been clarified in a number of places with additional
detail.
This commit also adds an additional section for the 'post-install'
process. This includes instructions for causing the relevant daemons /
subsystems to reload configuration data which is …

INSTALL.md: Update dependency list and rewrite / organize sections.

---

src/command-source.c
src/tcti-options.c

Found during internal security audit for inclusion for tpm2-abrmd in SUSE Linux distributions.

Security and Robustness Fixes

---

test/integration/get-capability-handles-transient.int.c

This test case was originally run by hand and the output verified by
whoever runs the test. This change makes the test automated in that it
will now fail if the handles returned by the GetCapability call aren't
the same as those returned by the calls to Load.

test: Check handles returned by GetCap against those returned by Load.

---

RELEASE.md

docs: Add documentation for release process.

---

CHANGELOG.md

CHANGELOG.md: Update for diff between 1.0.0 and 1.1.0 releases.

---

CHANGELOG.md
Makefile.am
scripts/int-log-compiler.sh
src/access-broker.c
src/command-source.c
src/resource-manager.c
src/response-sink.c
src/thread.c
src/thread.h
src/tpm2-command.c
src/tpm2-command.h
src/tpm2-response.c
src/tpm2-response.h
src/util.c
src/util.h
test/access-broker_unit.c
test/command-source_unit.c
test/integration/context-util.c
test/integration/main.c
test/integration/not-enough-handles-for-command.int.c
test/integration/tcti-connect-multiple.int.c
test/integration/test-options.c
test/integration/test-options.h
test/integration/tpm2-command-flush-no-handle.int.c
test/integration/util-buf-max-upper-bound.int.c
test/resource-manager_unit.c
test/thread_unit.c
test/tpm2-command_unit.c
test/tpm2-response_unit.c

Bit of an omnibus PR but the fixes to the test infrastructure here depended on a number of stability fixes. Also received some changes to related / overlapping parts of the code from @mgerstner which are included here as well.

Int log compiler check bins

---

CHANGELOG.md
configure.ac

Update version string and CHANGELOG.md for 1.1.1 release.

---

.travis.yml
test/command-source_unit.c
test/integration/common.c
test/integration/common.h
test/integration/password-authorization.int.c

Tpm2 emulator 974

---

CHANGELOG.md

CHANGELOG.md: Update documenting changes between 88e8770c and 7f0d8390.

---

.travis.yml
CHANGELOG.md
Makefile.am
bootstrap
configure.ac
src/command-source.c
src/command-source.h
src/connection.c
src/connection.h
src/response-sink.c
src/tabrmd.c
src/tcti-tabrmd-priv.h
src/tcti-tabrmd.c
src/util.c
test/access-broker_unit.c
test/command-source_unit.c
test/connection-manager_unit.c
test/connection_unit.c
test/message-queue_unit.c
test/resource-manager_unit.c
test/session-entry_unit.c
test/tpm2-command_unit.c
test/tpm2-response_unit.c
test/tss2-tcti-tabrmd_unit.c

This merge got a bit borked with duplicate commits between 1.x and master. Not sure how I made this happen but it should just be some extra noise that can be ignored.

Merge 1.x to master

---

src/command-source.c

This is in accordance with the guidance from the GObject destruction reference:
https://developer.gnome.org/gobject/stable/howto-gobject-destruction.html
I've also cleaned up a few comments here to make them less out of date.

CommandSource: Move freeing of GObjects to dispose instead of finalize.

---

Makefile.am
src/ipc-frontend-dbus.c
src/ipc-frontend-dbus.h
src/ipc-frontend.c
src/ipc-frontend.h
src/tabrmd.c
test/ipc-frontend-dbus_unit.c
test/ipc-frontend_unit.c

Should be the finishing touches on the abstractions to encapsulate IPC front-ends.

1.x abstract ipc frontend

---

src/response-sink.c
src/tcti-tabrmd.c
src/tpm2-command.c
src/util.c

This is a few (3) fixups to mostly benign issues.

1.x assorted fixes and cleanup

---

.gitignore
README.md
contrib/tabrmd.fc
contrib/tabrmd.if
contrib/tabrmd.te
src/ipc-frontend-dbus.c
src/ipc-frontend-dbus.h
src/response-sink.c
src/tcti-tabrmd.c
src/tpm2-command.c
src/util.c

This brings a number of fixes and features over from the 1.x branch to master.

merge 1.x into master

---

README.md

README.md: Fix broken link to TABRM draft spec.

---

src/access-broker.c
src/command-attrs.c
src/connection-manager.c
src/connection.c
src/handle-map.c
src/ipc-frontend-dbus.c
src/message-queue.c
src/resource-manager.c
src/response-sink.c
src/session-entry.c
src/session-list.c
src/tcti-device.c
src/tcti-echo.c
src/tcti-options.c
src/tcti-socket.c
src/tcti-tabrmd.c
src/tpm2-command.c
src/tpm2-response.c

Cleanup all of our GObjects to use the dispose & finalize functions properly.
This resolves #210

1.x gobject dispose cleanup

---

man/tpm2-abrmd.8.in

man: Document the new --allow-root option.

---

README.md

README.md: Account for 01org to intel Github org renaming.

---

CHANGELOG.md

CHANGELOG.md: Update for changes since 88e8770c.

---

CHANGELOG.md
CONTRIBUTING.md
Makefile.am
README.md
RELEASE.md
src/resource-manager.c
src/resource-manager.h
src/session-entry-state-enum.c
src/session-entry-state-enum.h
src/session-entry.c
src/session-entry.h
src/session-list.c
src/session-list.h
test/access-broker_unit.c
test/command-attrs_unit.c
test/command-source_unit.c
test/integration/session-load-from-closed-connection.int.c
test/integration/session-load-from-closed-connections-lru.int.c
test/integration/session-load-from-open-connection.int.c
test/random_unit.c
test/resource-manager_unit.c
test/tcti-device_unit.c
test/tcti-socket_unit.c
test/tss2-tcti-tabrmd_unit.c
test/util_unit.c

this is routine merge of new features from the release branch back into master

merge 1.x back into master

---

.gitignore
Makefile.am

build: Generate AUTHORS file from git. Include it in release tarballs.

---

scripts/int-log-compiler.sh

This is effectively port assignment collision detection. If the
simulator we start isn't bound to both ports we consider it an error. We
then kill the simulator and try again after an exponential backoff
period. If the simulator is able to bind to the data port but not the
command port it will still run but tests will fail. Killing it off is
important to keep from leaving tpm_server instances around.

build: Check that simulator has bound both ports.

---

test/random_unit.c

unit: Remove unnecessary NULL from final element in CMUnitTest array.

---

test/integration/session-load-from-closed-connections-lru.int.c

fix spelling mistake

---

test/integration/session-load-from-closed-connections-lru.int.c
test/tss2-tcti-tabrmd_unit.c

these are cherry-picks from master than should have gone into 1.x first

1.x fix tcti test

---

.travis.yml
Makefile.am
configure.ac
test/random_unit.c

This resolves #268 and gets us more accurate coverage metrics in coveralls.

1.x fix random unit

---

Makefile.am
src/logging.c
src/logging.h
test/logging_unit.c

test: Add unit test for logging module.

---

Makefile.am
src/resource-manager.c
test/integration/auth-session-max.int.c
test/integration/session-load-from-closed-connection.int.c

1.x bugfix session save across closed connection

---

README.md

README.md: Account for org move to tpm2-software.

---

src/ipc-frontend-dbus.c
src/tcti-tabrmd.c

This commit is try to fix this issue #96 .
Signed-off-by: Lu Gong <lu.gong@intel.com>

Fix the inappropriate use of g_error with GError.

---

CHANGELOG.md

CHANGELOG.md: Update with data for first 1.3.0 release candidate.

---

src/tcti-dynamic.c
src/tcti-echo.c
src/tcti.c
test/integration/context-util.c
test/integration/not-enough-handles-for-command.int.c
test/integration/tcti-cancel.int.c
test/integration/tcti-connect-multiple.int.c
test/integration/tcti-set-locality.int.c
test/integration/tpm2-command-flush-no-handle.int.c
test/integration/util-buf-max-upper-bound.int.c
test/tss2-tcti-echo_unit.c
test/tss2-tcti-tabrmd_unit.c

These updates bring us up to date with the latest TCG specs that just
went through public review.

Update our TCTI implementation to align with upstream changes.

---

CHANGELOG.md

Made a few minor wording changes in one bullet as well.

CHANGELOG.md: Add date and version for 1.3.0 release.

---

CHANGELOG.md

This is in anticpation of starting an rc0 for 1.3.1.

CHANGELOG.md: Add entry for fix to preset file distribution.

---

src/tpm2-command.c
src/util.c
test/integration/password-authorization.int.c

Account for changes to TPMA_* constants upstream.

---

README.md

doc: Update coveralls URLs in README.md

---

CHANGELOG.md

CHANGELOG.md: Add date for 1.3.1 release.

---

.travis.yml

Add scan-build Static Code Analysis to Travis

---

Makefile.am
src/resource-manager.c
src/session-entry-state-enum.h

New sessions on loaded session list

---

Makefile.am
src/handle-map.c
test/integration/max-transient-upperbound.int.c

Test max transient

---

src/resource-manager.c

This PR fixes two bugs related to object management in the ResourceManager. 
130be5b resolves #458

ResourceManager GQueue cleanup fix

---

CHANGELOG.md

This commits fill in data for past commits. This resolves #461.

CHANGELOG.md: Update in anticipation of the 2.0 release.

---

src/resource-manager.c
src/resource-manager.h
test/resource-manager_unit.c

This PR consists of a few commits that cleanup:
1) comment blocks
2) function and variable names
3) minor logic
for the sake of making them more accurate / clear.

RM refactor

---

src/resource-manager.c
src/tpm2-response.c

These tree commits are some unrelated cleanup and refactoring.

random RM cleanup

---

src/resource-manager.c
src/resource-manager.h
src/session-entry-state-enum.c
src/session-entry-state-enum.h
test/resource-manager_unit.c

simplification in the ResourceManager and a fix for a race condition

remove loaded session list

---

test/integration/tcti-connect-multiple.int.c

test: Fix memory management mistake in test.

---

src/resource-manager.c

0115d572bc4f6026a28a2ed5d7340ca77c6dc4d2 fixed the worst part of this
but a very narrow window for a race persisted. For it to trigger the
client must terminate their connection to the daemon triggering a call
to the resource_manager_on_connection_removed function by an external
thread before the main processing thread saves all of the sessions
associated with the previous command.
Fixing this requires that the main processing loop hold the lock on the
SessionList until all sessions have been saved.

ResourceManager: Fix race between session save and connection termination.

---

CHANGELOG.md

Preparing for a bugfix release.

CHANGELOG.md: Add data for fixes to dynamic TCTI loading and race.

---

CHANGELOG.md
src/tcti-tabrmd.c
src/util.c

1.3.2 cherries

---

CHANGELOG.md

Update CHANGELOG.md in anticipation of another bugfix release.

---

.travis.yml

Upgrade travis build image and clean up the `.travis.yml` file.

Travis xenial

---

CHANGELOG.md

Update CHANGELOG.md for 2.1.0.

---

.travis.yml

this is a good candidate for squashing

1.x ci urls

---

CHANGELOG.md

CHANGELOG: Add entry for 1.3.3 release.

---

.codecov.yml
.travis.yml
README.md

ci: switch from coveralls to codecov

---

Makefile.am
src/ipc-frontend-dbus.c
src/tabrmd-defaults.h
src/tabrmd-options.c
src/tabrmd-options.h
src/tabrmd.c
src/tabrmd.h
src/tcti-tabrmd-priv.h
test/command-source_unit.c
test/connection-manager_unit.c
test/integration/auth-session-max.int.c
test/integration/max-transient-upperbound.int.c
test/integration/session-load-from-closed-connections-lru.int.c
test/integration/tcti-connections-max.int.c
test/tabrmd-options_unit.c

Tabrmd options refactor

---

Makefile.am
src/tabrmd-init.c
src/tabrmd-init.h
src/tabrmd.c
test/tabrmd-init_unit.c

Tabrmd refactor init

---

dist/tpm2-abrmd.service.in

Service unit fixes

---

selinux/tabrmd.te

Reverts tpm2-software/tpm2-abrmd#678

Revert "Update SELinux policy for network TCTI connections"

---

CHANGELOG.md

CHANGELOG.md: Update for 2.3.1 release.

---

Makefile.am
src/access-broker.c
src/access-broker.h
test/access-broker_unit.c

Access broker cleanup

---

Makefile.am
scripts/int-test-funcs.sh
src/access-broker.c
src/access-broker.h
test/access-broker_unit.c

General cleanup and improvements to test coverage.

Access broker coverage

---

.travis.yml
src/tpm2.c

Fix asserts

---

MAINTAINERS

Seems I made one of these for the other tpm2-tss projects but missed
this one. Adding myself.

Add MAINTAINERS file.

---

src/tpm2-command.c
src/tpm2-command.h
test/tpm2-command_unit.c

Tpm2Command: Remove unused function.

---

README.md

README: update build status to GH Actions

---

.ci/docker.run
.github/workflows/docker.yml
Makefile.am
configure.ac
scripts/int-test-setup.sh
src/handle-map.c
src/resource-manager.c
src/session-list.c
src/tabrmd-init.c
src/tabrmd-init.h
src/tabrmd-options.c
src/tabrmd-options.h
src/tabrmd.c
src/tpm2-response.c
src/tpm2-response.h
test/command-attrs_unit.c
test/integration/context-util.c
test/integration/context-util.h
test/integration/tcti-connections-max.int.c
test/resource-manager_unit.c
test/session-list_unit.c
test/tabrmd-init_unit.c
test/tabrmd-options_unit.c
test/tpm2_unit.c

1. Add ASAN support in configure script via --configure-asan
2. Add ASAN enabled builds to clang builds and tests
3. Fix memory leaks and issues
I **think** this:
Fixes: #740

Fix mem leak

---

INSTALL.md
configure.ac

Related to:
https://github.com/tpm2-software/tpm2-tss/issues/2016

Add missing install deps

---

man/tpm2-abrmd.8.in

I believe it is quite important to document what exactly is the default behavior.

doc: explicitly describe the defaults

---

.github/workflows/main.yml

ci: drop ubuntu-16.04

---

CHANGELOG.md

Update CHANGELOG.md for 2.4.1 release.

---

.cirrus.yml

Upgrade cirrus FreeBSD image version from 12.2 to 12.3.

---

.cirrus.yml

cirrus: update family image to 13-1

---

CHANGELOG.md

CHANGELOG: update for 3.0.0-rc0

---

selinux/tabrmd.if

Fix typo and whitespace from 2075b851.
